---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: false

platforms:
- name: debian-wheezy
  driver_config:
    box: debian-wheezy
    box_url: http://projects.tsuntsun.net/~nabeken/boxes/vagrant-debian-wheezy.box
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[php_fpm]
  - recipe[php_fpm::www]
  - recipe[php_fpm_test::www_template]
  - recipe[minitest-handler]
